# Server configuration
server.port=8080

# Spring Application Name
spring.application.name=sevasarthi-backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/seva-sarthi-java

# JWT Configuration (Replace with actual secrets in production)
jwt.secret=your_super_secret_key_which_must_be_at_least_256_bits_long_for_hs256_algorithm
jwt.expirationMs=86400000

# Razorpay Configuration
razorpay.key_id=
razorpay.key_secret=

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
